#!/bin/bash

[ -d /usr/src/app ] || {
  echo "This script is intended to be executed inside the docker container."
  echo "To develop locally, run:"
  echo
  echo " source ./environment.sh"
  echo " docker-compose up"
  echo
  exit 1
}

cd /usr/src/app

[ -d node_modules ] || npm install .

case "${ACTION}" in
  test)
    npm test
    ;;
  *)
    nodemon app.js
    ;;
esac
