#!/bin/bash

ROOT=$(cd $(dirname ${0})/.. ; pwd)

cd ${ROOT}
if [ -f ${ROOT}/environment-integration.sh ]; then
  source ${ROOT}/environment-integration.sh
else
  source ${ROOT}/environment.sh
fi

export ACTION="test"
export INTEGRATION="true"
export STORAGE="remote"

exec docker-compose up
